linux_display_server x11
# background

background_opacity 1.0

# smooth scrooling

momentum_scroll 0.96

# tab bar

tab_bar_edge top
tab_bar_style powerline

# general

confirm_os_window_close 0
enable_audio_bell no


# BEGIN_KITTY_FONTS
font_family      family="FantasqueSansM Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS